name: CI Notifikasi Tugas

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '*/2 * * * *'

jobs:
  notifikasi-dan-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: List isi folder backend (debug)
      run: ls -la backend

    - name: Init database (create tables)
      run: PYTHONPATH=. python backend/init_db.py

    - name: Jalankan pengecekan deadline
      run: PYTHONPATH=. python backend/cek_deadline.py

    - name: Jalankan test API dengan pytest
      run: PYTHONPATH=. pytest tests/
