name: Notifikasi Tugas

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  kirim-notifikasi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: List isi folder backend
      run: ls -la backend

    - name: Init database (create tables)
      run: PYTHONPATH=. python backend/init_db.py

    - name: Jalankan pengecekan deadline
      run: PYTHONPATH=. python backend/cek_deadline.py


